### ISSUE TITLE
Snippets in templates

### ISSUE THREAD

**Issue by pepa-linha** [nepada/form-renderer#135]
Hi,

is it possible to use snippets in defined blocks in some way?

I am getting an error

Call to a member function getHtmlId() on null

in generated template

```php
echo ' id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('snippetName')), '"';
```

... Maybe pass custom variables and then call a method to get the snippet ID.

**Comment by xificurk** [comment]
In short - no. There is no Nette Application `Control` to handle the snippets in the template used to render the form, so snippets cannot be used.

You could have a custom form control that also extends Control from Nette Application (something like https://github.com/nextras/form-components) with its own template. This control could then render itself by Latte template with snippets (same as any other component).
